added creating themes
mautic/user-documentation pull request #114
Opened 2022-10-30 21:54 UTC by favour-chibueze

TED-132

2022-10-30 21:56 UTC, favour-chibueze commented
@RCheesley Please review this

2022-11-21 11:56 UTC, RCheesley requested changes
Teeny tiny suggestion then all good! 🚀

2022-11-21 11:56 UTC, RCheesley commented on docs/builders/creating_themes.rst
> +Once your design in MJML is final, go through the following steps to create the Theme package:
```suggestion
Once your design in MJML is finalized, go through the following steps to create the Theme package:
```

2022-12-08 21:35 UTC, favour-chibueze commented
@RCheesley

2022-12-09 10:47 UTC, RCheesley requested changes
A few small suggestions:

- GrapesJS has both letters capitalised in the JS part
- Added language to json code block for better visuals
- Added a small note about zipping the file as I and many others have made that mistake too many times to mention!

2022-12-09 10:47 UTC, RCheesley commented on docs/builders/creating_themes.rst
> +The GrapesJs builder makes it possible to insert HTML code and edit it in a 'What You See Is What You Get' (WYSIWYG) environment.
```suggestion
The GrapesJS builder makes it possible to insert HTML code and edit it in a 'What You See Is What You Get' (WYSIWYG) environment.
```

2022-12-09 10:47 UTC, RCheesley commented on docs/builders/creating_themes.rst
> +:xref:`MJML` enables marketers to create and maintain beautiful and responsive Themes for Mautic easily.
```suggestion
:xref:`MJML` allows marketers to create and maintain beautiful and responsive Themes for Mautic easily.
```

2022-12-09 10:47 UTC, RCheesley commented on docs/builders/creating_themes.rst
> +The GrapesJs Builder checks the Theme configuration file before listing the available Themes, to determine which are compatible with the Builder.
```suggestion
The GrapesJS Builder checks the Theme configuration file before listing the available Themes, to determine which are compatible with the Builder.
```

2022-12-09 10:47 UTC, RCheesley commented on docs/builders/creating_themes.rst
> +.. code-block::
```suggestion
.. code-block:: json
```

2022-12-09 10:47 UTC, RCheesley commented on docs/builders/creating_themes.rst
> +It's possible to use HTML for Themes, and the GrapesJs builder offers basic WYSIWYG editing capabilities.
```suggestion
It's possible to use HTML for Themes, and the GrapesJS builder offers basic WYSIWYG editing capabilities.
```

2022-12-09 10:47 UTC, RCheesley commented on docs/builders/creating_themes.rst
> +* Create a thumbnail - around 400px wide, 600px high.
```suggestion
* Create a thumbnail - use the dimensions of 400px wide, 600px high.
```

2022-12-09 10:47 UTC, RCheesley commented on docs/builders/creating_themes.rst
> +* Compress the contents of the folder as a Zip file
```suggestion
* Compress the contents of the folder as a Zip file - ensure that the files and folders aren't within a sub-folder in the Zip file.
```

2022-12-09 10:47 UTC, RCheesley commented on docs/builders/creating_themes.rst
> +* Compress the contents of the folder as a Zip file
This is a common mistake that folks make.

2022-12-26 20:30 UTC, favour-chibueze commented
@RCheesley

2023-01-09 12:30 UTC, RCheesley approved these changes
LGTM! 🚀

2023-01-09 12:30 UTC, merged