Update campaign_builder.rst - Added Transactional No DNC text to M5 branch
mautic/user-documentation pull request #136
Opened 2023-01-13 12:31 UTC by jos0405

Added Transactional No DNC text to M5 branch

2023-01-20 14:46 UTC, RCheesley requested changes
I think it would be best to have a section on the Channels > emails.rst file which explains Transactional v Marketing (and maybe also Personal emails and form results emails) with the key differences.

We could then link to it from within this table, making it less of a wall of text in a small table cell!

WDYT @jos0405 ?

2023-01-20 14:46 UTC, RCheesley commented on docs/campaigns/campaign_builder.rst
> +     - Emails can be transactional or marketing. Marketing emails will obey Email Channel's Do Not Contact setting of the contact, Transactional Emails will disregard the Do Not Contact value. This a
```suggestion
     - Sends a transaction or marketing Email to the selected Contact. You can send a transactional Email to the Contact multiple times. You can only send a marketing Email to the Contact once across multiple sources. If the Contact has already received this Email from another source or the current Campaign, they aren't sent the Email again and the Contact progresses through the Campaign. Emails can be transactional or marketing. Marketing Emails obey Do Not Contact (DNC) settings of the Contact, Transactional Emails disregard the DNC value. This allows sending Transactional Emails as a Campaign step to Contacts, even if they opted out to receive marketing Emails via a standard unsubscribe action and therefore have DNC set for the Email Channel. Turned on by default in Mautic 5.0, it's possible to override the setting in Email Settings.
```

Just like we test code PR's in Gitpod, please review your docs edits in Gitpod too! This one broke the RST table layout, and there were several Vale fixes to do after addressing that 😸 .

There should be a Gitpod button to click and you'll see any issues in the 'output' tab.

As a side thought, this is a big wall of text to have in a small area in a table. Maybe it makes more sense to have a dedicated section which explains transactional and marketing emails, and link to it from this with a small description? WDYT @jos0405 ? I think a sub-section of emails.rst under Channels would make the most sense.

2023-01-20 14:46 UTC, RCheesley commented on docs/campaigns/campaign_builder.rst
>       - Sends a transaction or marketing Email to the selected Contact. You can send a transactional Email to the Contact multiple times. You can only send a marketing Email to the Contact  once acros
```suggestion
```

2024-01-09 18:55 UTC, RCheesley commented
@jos0405 would you be up for refactoring this based on the feedback? I feel it's too much of a wall-of-text to go into a table as it stands.

2025-08-06 08:28 UTC, adiux commented
@jos0405 I think we should get this merged, as the related PR is also merged. Could you look into it?

2025-08-06 08:30 UTC, adiux commented
I'm actually a bit confused. Does it remove the unsubscribe header only from the transactional emails? Or also from the individual emails (sent from the contact details page), as it says in the PR description: 
> This PR removes an unsubscribe header from an individual and transactional emails.

From my tests it only removes it from the transactional emails.

2025-12-11 08:02 UTC, adiati98 commented on docs/campaigns/campaign_builder.rst
>       - Sends a transaction or marketing Email to the selected Contact. You can send a transactional Email to the Contact multiple times. You can only send a marketing Email to the Contact  once acros
@RCheesley I'm not quite understand about the content. But from your responses here, can we link the KB article (https://kb.mautic.org/article/understand-the-difference-transactional-and-marketing-emails-in-mautic.html) here like so:

```suggestion
* - **Send Email**   
  - Sends a transactional or marketing Email to the selected Contact. Learn more about transactional and marketing Email in (this article).
```

2025-12-30 16:17 UTC, adiati98 commented on docs/campaigns/campaign_builder.rst
>       - Sends a transaction or marketing Email to the selected Contact. You can send a transactional Email to the Contact multiple times. You can only send a marketing Email to the Contact  once acros
If that's okay, I can help to apply it.

2026-01-29 07:56 UTC, adiati98 commented
@mautic/core-team can you help to review the content here? TIA! ✨

2026-01-29 08:28 UTC, escopecz commented
Once https://github.com/mautic/mautic/pull/14019 is merged then this will need another overhaul. Perhaps we could wait for that?

2026-02-02 23:38 UTC, RCheesley commented on docs/campaigns/campaign_builder.rst
>       - Sends a transaction or marketing Email to the selected Contact. You can send a transactional Email to the Contact multiple times. You can only send a marketing Email to the Contact  once acros
Yes, I think that's fine, using a link macro

2026-02-04 15:02 UTC, adiati98 commented
@RCheesley the build failed here because of timeout from this newly added URL: https://kb.mautic.org/article/how-to-integrate-mautic-with-salesforce.html.

Should we include this in the `accept.txt`?

2026-02-05 15:55 UTC, merged

2026-02-05 15:55 UTC, RCheesley commented
I reran and it works so all good!