[DPMMA-2108] Add UTM to Asset download #12098
mautic/user-documentation pull request #157
Opened 2023-05-05 07:39 UTC by tomekkowalczyk

2023-05-05 10:38 UTC, RCheesley requested changes
Small suggestion and I think it should move to the creating an asset section - see what you think! I'll make another PR to fix the incorrect headings further up the page.

2023-05-05 10:38 UTC, RCheesley commented on docs/components/assets.rst
> +You can add a resource of UTM parameters to the download link. We can use UTM data in the resource download report.
```suggestion
UTM parameters appended to the download link means that UTM data is available in the resource download Report.
```

Fix the style - Vale is flagging a warning due to the use of '[We](https://github.com/mautic/user-documentation/actions/runs/4891096079/jobs/8731311211?pr=157#step:4:30)' and the lack of capitalisation of [Report](https://github.com/mautic/user-documentation/actions/runs/4891096079/jobs/8731311211?pr=157#step:4:38).

I actually think that this fits better in the Creating Assets section, as that's when the user is most likely to need to have this information - what do you think?

2023-05-08 06:00 UTC, tomekkowalczyk commented
@RCheesley Looks good, I changed the sections to Create Asset.

2023-05-16 14:38 UTC, merged

2023-05-16 14:38 UTC, RCheesley commented
@all-contributors please add @tomekkowalczyk for docs