[DPMMA-2044] Builder custom fonts
mautic/user-documentation pull request #162
Opened 2023-05-25 14:16 UTC by annamunk

Docs for https://github.com/mautic/grapesjs-preset-mautic/pull/43 and https://github.com/mautic/mautic/pull/12067

2023-05-25 14:40 UTC, RCheesley requested changes
Thanks for making the PR @annamunk! Just a couple of fixes suggested by the linter to change the text from passive to active, and I think we should mention the version from which these changes will be applied.

2023-05-25 14:40 UTC, RCheesley commented on docs/builders/email_landing_page.rst
> +The Style Manager > Typography > Fonts list can be extended to include custom fonts.
```suggestion
From Mautic 4.4.9 you can extend the Style Manager > Typography > Fonts list to include custom fonts.
```

Vale fix for grammar, and also mentioning the version from which you will be able to do this (assuming it goes into 4.4.9 and also 5.x).

2023-05-25 14:40 UTC, RCheesley commented on docs/builders/email_landing_page.rst
> +New options are defined as elements of the ``'editor_fonts'`` array in the local configuration file (most cases ``app/config/local.php``). The font should have a unique name and a valid css style url
```suggestion
You define options as elements of the ``'editor_fonts'`` array in the local configuration file - in most cases located in ``app/config/local.php``. The font should have a unique name and a valid CSS style URL. See example below:
```

Vale fix for active voice.

2023-05-25 14:52 UTC, annamunk commented
@RCheesley thank you! I will add suggested the fixes. 
In the Mautic repository, the changes seem to have been merged into version 5.x. Should I prepare there related PR with this functionality for 4.x branch, so it can be released from version 4.4.9?

2023-05-25 16:53 UTC, annamunk commented
@RCheesley I corrected the documentation. Could you please take a look again?

2023-06-15 12:52 UTC, RCheesley approved these changes

2023-06-15 12:54 UTC, merged

2023-06-15 12:54 UTC, RCheesley commented
Thanks @annamunk - merged on the preset repo and the mautic/mautic repo is already merged, so good to go!