Campaign priority description
mautic/user-documentation pull request #200
Opened 2023-09-20 10:46 UTC by patrykgruszka

Docs for the https://github.com/mautic/mautic/pull/12721

2023-10-27 10:20 UTC, fakela commented
This looks good to me @RCheesley please take a look

2023-10-27 11:43 UTC, RCheesley requested changes
Just a couple of small vale fixes.

2023-10-27 11:43 UTC, RCheesley commented on docs/campaigns/creating_campaigns.rst
> +-  **Priority** - Choose a priority for your campaign. Campaigns with higher priority will be processed before campaigns with normal priority.
```suggestion
-  **Priority** - Choose a priority for your Campaign. Campaigns with higher priority will be processed before Campaigns with normal priority.
```

Vale fixes

2023-11-01 10:16 UTC, RCheesley requested changes
Just one thing flagged up now that Reviewdog/Vale is working again then we are good to go!

Just one question @patrykgruszka - is this something being merged into Mautic 5, or is it in 4 as well? Main is for 4.x and the 5.x branch is for 5.0 so it may require a rebase.

2024-04-16 16:47 UTC, RCheesley commented
@patrykgruszka this one needs rebasing please, to the 5.x branch! Thanks!

2024-04-17 08:40 UTC, patrykgruszka commented
This change will not be implemented. I am closing this PR

2024-04-17 08:40 UTC, closed without merging

2024-04-17 10:36 UTC, RCheesley commented
OK thanks!