Change “Render style from Template?” to “Use theme style?” when creating form #13369
mautic/user-documentation pull request #283
Opened 2024-04-16 14:09 UTC by fakela

2024-04-16 14:23 UTC, RCheesley requested changes
Just a tiny Vale fix then GTG!

2024-04-16 14:23 UTC, RCheesley commented on docs/components/forms.rst
> +- **Use theme style** - If Yes, the Form displays with the styling from either the selected Mautic Theme or the Attributes tab of the Form Fields. When No, the Form adopts the styling of where it's e
```suggestion
- **Use Theme style** - If Yes, the Form displays with the styling from either the selected Mautic Theme or the Attributes tab of the Form Fields. When No, the Form adopts the styling of where it's embedded.
```

2024-04-17 22:46 UTC, fakela commented
@RCheesley comment resolved

2024-04-18 13:21 UTC, RCheesley approved these changes

2024-04-19 17:26 UTC, RCheesley approved these changes
GTG! 🚀

2024-06-13 12:59 UTC, merged