[UX] Reorder administration panel
mautic/user-documentation pull request #292
Opened 2024-04-17 17:43 UTC by andersonjeccel

For https://github.com/mautic/mautic/pull/13596

2024-04-18 13:24 UTC, RCheesley commented on docs/plugins/images/plugins.png
Is there a reason to change the colour used? As we tend to stick with red.

2024-04-18 14:14 UTC, andersonjeccel commented on docs/plugins/images/plugins.png
Hm, no reason (it was the default of the Photos app)
Would it be a problem?

2024-06-13 14:11 UTC, RCheesley requested changes
Just need to update the image so it's using a red underline instead of blue, please!

2024-06-13 14:11 UTC, RCheesley commented on docs/plugins/images/plugins.png
Could we have this one with a red line rather than blue please @andersonjeccel , to keep in context with the ret of the docs?

2024-06-13 14:34 UTC, andersonjeccel commented on docs/plugins/images/plugins.png
@RCheesley Fixed

2024-06-18 15:52 UTC, RCheesley approved these changes

2024-06-18 15:53 UTC, merged