DPMMA-2688 Smart Campaign Event Scheduling Based on Contact Behavior
mautic/user-documentation pull request #302
Opened 2024-05-06 13:15 UTC by patrykgruszka

Docs for PR: https://github.com/mautic/mautic/pull/13569

2024-05-07 10:03 UTC, RCheesley requested changes
Just some small improvements to use hyphens instead of brackets - does this work?

2024-05-07 10:03 UTC, RCheesley commented on docs/campaigns/campaign_builder.rst
> +2. **Minimum interactions requirement**: a Contact must have a minimum number of interactions for the system to calculate optimal timing. Each interaction type (Email open, website visit, Form submit
```suggestion
2. **Minimum interactions requirement**: a Contact must have a minimum number of interactions for the system to calculate optimal timing. Each interaction type - Email open, website visit, Form submit - counts only once per hour. When a Contact doesn't have enough interaction data, default hour ranges and days adjust to the Contact's preferred timezone.
```

2024-05-07 10:03 UTC, RCheesley commented on docs/campaigns/campaign_builder.rst
> +3. **Optimal time calculation (execute event within 24 hours)**: based on the Contact's interaction data, the system calculates the optimal time for executing a Campaign event, considering the Contac
```suggestion
3. **Optimal time calculation - execute event within 24 hours**: based on the Contact's interaction data, the system calculates the optimal time for executing a Campaign event, considering the Contact's historical engagement patterns.
```

2024-05-07 10:03 UTC, RCheesley commented on docs/campaigns/campaign_builder.rst
> +4. **Optimal date calculation (execute event within 7 days)**: the system calculates the optimal time as in the previous option and additionally determines the best day of the week. By default, a Con
```suggestion
4. **Optimal date calculation - execute event within 7 days**: the system calculates the optimal time as in the previous option and additionally determines the best day of the week. By default, a Contact can have multiple optimal days.
```

2024-07-04 07:47 UTC, patrykgruszka commented
Thanks @RCheesley, I've added your suggestions

2024-07-04 08:35 UTC, RCheesley requested changes
Suggested some fixes for the issues Vale has flagged up.

2024-07-04 08:35 UTC, RCheesley commented on docs/configuration/settings.rst
> +* **Default Optimal Days** - Select the default days of the week that are considered optimal for interaction when specific Contact data is unavailable.
```suggestion
* **Default Optimal Days** - Select the default days of the week considered optimal for interaction when specific Contact data is unavailable.
```

2024-07-04 08:35 UTC, RCheesley commented on docs/configuration/settings.rst
> +* **Interaction Data Cache Timeout** - Choose how long the interaction data should be cached.
```suggestion
* **Interaction Data Cache Timeout** - Choose how long to cache the interaction data for.
```

2024-07-04 08:35 UTC, RCheesley commented on docs/configuration/settings.rst
> +* **Fetch Interactions From** - Select the time frame for fetching interaction data. This determines how far back the system will look for interactions.
```suggestion
* **Fetch Interactions From** - Select the time frame for fetching interaction data. This determines how far back to look for interactions.
```

2024-07-04 08:35 UTC, RCheesley commented on docs/configuration/settings.rst
> +* **Interaction Fetch Limit** - Set the maximum number of interactions of each type (for example: Page hits, Email reads, Form submits) to retrieve for timing optimization.
```suggestion
* **Interaction Fetch Limit** - Set the maximum number of interactions of each type - for example: Page hits, Email reads, Form submits - to retrieve for timing optimization.
```

2024-07-08 09:26 UTC, patrykgruszka commented
I've updated the docs, thanks @RCheesley!

2024-08-28 17:23 UTC, RCheesley approved these changes

2024-08-28 17:24 UTC, RCheesley commented
The accompanying PR to this has conflicts so I am guessing it will be released in 5.2. I'll milestone it in the docs accordingly and we will merge accordingly.

2024-12-03 11:57 UTC, patrykgruszka commented
@RCheesley I think we can merge this one, as 5.2 is released with this feature.

2025-01-14 15:57 UTC, merged