Added Tip to Variables for using Custom Company Fields
mautic/user-documentation pull request #310
Opened 2024-06-14 12:46 UTC by oltmanns-leuchtfeuer

The documentation lacks a hint, that the syntax for using core company fields as tokens and custom created onces is different.

I added a small "Tip" to briefly explain this difference.

2024-06-14 14:15 UTC, RCheesley requested changes
Query on a couple of things! Thanks for re-doing the PR @oltmanns-leuchtfeuer

2024-06-14 14:15 UTC, RCheesley commented on docs/configuration/variables.rst
> +  The syntax for custom Company fields is different than the core Company field syntax. You must **not** add the word "Company" in the variable, but instead treat it like a "contactfield":
Here it looks like you're going on to provide an example, but I can't see one. Is that intentional?

Also Vale picked up on the use of contactfield - do you mean Contact field?

2024-11-03 14:33 UTC, RCheesley commented
Hey @oltmanns-leuchtfeuer one for you to pick up in the community sprint maybe 😉

2026-01-28 09:10 UTC, adiati98 commented
I've cherry-picked this PR in #327. Therefore, I'm closing this. Thanks for the contribution!

2026-01-28 09:10 UTC, closed without merging

2026-03-11 12:34 UTC, RCheesley commented
I think maybe you meant to say #628 for the new PR, as the linked issue seems to not be relevant - just in case folks follow the link and get confuzzled! :)  Thanks for getting this over the line @adiati98!