Update forms.rst
mautic/user-documentation pull request #316
Opened 2024-09-08 16:36 UTC by putzwasser

Added the tokens that can be used in a form submit action.

2024-10-02 23:52 UTC, RCheesley requested changes
Thanks for the PR - a couple of small fixes for grammar rules.

2024-10-02 23:52 UTC, RCheesley commented on docs/components/forms.rst
> +    - `{contactfield=ALIAS}` replacing it with the value of the current contact's field, if any.
```suggestion
    - `{contactfield=ALIAS}` replacing it with the value of the current Contact's field, if any.
```

Vale fix

2024-10-02 23:52 UTC, RCheesley commented on docs/components/forms.rst
> +    - `{formfield=ALIAS}` replacing it with the value entered into the specified form field, if any.
```suggestion
    - `{formfield=ALIAS}` replacing it with the value entered into the specified Form field, if any.
```

Vale fix

2024-10-02 23:52 UTC, RCheesley commented on docs/components/forms.rst
> +    - `{pagelink=PAGE_ID}` replacing it with an absolute URL to the page having the specified ID.
```suggestion
    - `{pagelink=PAGE_ID}` replacing it with an absolute URL to the page with the specified ID.
```

2024-10-03 16:45 UTC, RCheesley commented
This is good to go when 5.2 is released, thanks @putzwasser 🚀

2024-11-03 14:26 UTC, RCheesley approved these changes

2024-11-03 14:28 UTC, RCheesley commented
@putzwasser please can you rebase this onto the 5.x branch, as that's the current active branch for the user docs. That will fix the failing linters.

2026-01-26 15:34 UTC, adiati98 commented
I've cherry-picked this PR in:

- https://github.com/mautic/user-documentation/pull/623 (branch `5.2`)

So, I'm closing this now.

Thanks for the contribution, @putzwasser! ✨

2026-01-26 15:34 UTC, closed without merging