Adds documentation for mautic/mautic/pull/14100
mautic/user-documentation pull request #317
Opened 2024-09-09 00:15 UTC by putzwasser

Adds documentation for PR https://github.com/mautic/mautic/pull/14100

2024-11-03 14:20 UTC, RCheesley requested changes
Thanks for the PR @putzwasser - you need to use the command `make link` to create the link file and commit it, then you can use the xref macro where the link is.

I've also made a Vale suggestion for the passive to active speech warning which will need implementing anywhere you've used it, please. Thanks!

2024-11-03 14:20 UTC, RCheesley commented on docs/components/forms.rst
> +   - **Date** - This field allows the visitor to select a date with a calendar picker. The formatting of the date applies the default setting in your Configuration. [A PHP parseable BNF-like string](
Hi @putzwasser please use the command `make link` at the terminal, follow the steps and then use the xref macro here. For info, if you're doing internal linking check the docs on using the [:ref: role](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#the-ref-role) for linking within the same document, and using [:doc: to link across pages](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#the-doc-role).

Please fix this in all the places you've mentioned it. Thanks!

2024-11-03 14:20 UTC, RCheesley commented on docs/components/forms.rst
> +   - **Date** - This field allows the visitor to select a date with a calendar picker. The formatting of the date applies the default setting in your Configuration. [A PHP parseable BNF-like string](
```suggestion
   - **Date** - This field allows the visitor to select a date with a calendar picker. The formatting of the date applies the default setting in your Configuration. You can use [A PHP parseable BNF-like string](https://www.php.net/manual/en/datetime.formats.php) to set a dynamic/relative to now default value for this field.
```

Passive -> Active voice

2026-01-26 09:33 UTC, adiati98 commented
I've cherry-picked this PR in:

- https://github.com/mautic/user-documentation/pull/621 (branch 7.0)
- https://github.com/mautic/user-documentation/pull/622 (branch 7.1).

So, I'm closing this now.

Thanks for the contribution, @putzwasser! ✨

2026-01-26 09:33 UTC, closed without merging