Documenting the resubscribe_url token
mautic/user-documentation pull request #342
Opened 2024-11-08 08:52 UTC by escopecz

Related to https://github.com/mautic/mautic/pull/14215

2024-11-12 14:44 UTC, RCheesley requested changes
Some small Vale fixes!

2024-11-12 14:44 UTC, RCheesley commented on docs/channels/emails.rst
> +- ``{resubscribe_url}``: Inserts the URL to the resubscribe page no matter if the preference center is activated or not. It will resubscribe the contact. Useful for double opt out campaigns.
```suggestion
- ``{resubscribe_url}``: inserts the URL to the resubscribe page regardless of whether there's a preference centre in use. It resubscribes the Contact. Useful for double opt out Campaigns.
```

Vale fixes

2024-11-12 15:08 UTC, escopecz commented on docs/channels/emails.rst
> +- ``{resubscribe_url}``: Inserts the URL to the resubscribe page no matter if the preference center is activated or not. It will resubscribe the contact. Useful for double opt out campaigns.
Thanks!

2026-01-25 09:23 UTC, adiati98 commented
@RCheesley the build fails here, but I can't see what's going on because the log is expired and I can't re-run the job. If nothing is concerning, we can go ahead and merge this PR.

2026-02-02 23:53 UTC, RCheesley commented
Seems to be broken links, just closed and reopened to trigger a rerun.

2026-02-03 06:32 UTC, adiati98 commented
@RCheesley I've fixed the building failed here. 👍🏼

2026-02-05 15:56 UTC, RCheesley approved these changes

2026-02-05 15:56 UTC, merged