added categories page
mautic/user-documentation pull request #40
Opened 2022-04-05 20:57 UTC by favour-chibueze

2022-04-06 12:00 UTC, RCheesley requested changes
Thanks for this PR @favour-chibueze - I think maybe you have not got Vale running because these should be picked up by Vale and alerting you to fix them.

Shout if you need help setting this out!

2022-04-06 12:00 UTC, RCheesley commented on docs/categories/categories-overview.rst
> +Contact categories can be used in segment and dynamic content filters.
```suggestion
Contact Categories can be used in Segment and Dynamic Content filters.
```

2022-04-06 12:39 UTC, favour-chibueze commented
> Thanks for this PR @favour-chibueze - I think maybe you have not got Vale running because these should be picked up by Vale and alerting you to fix them.
> 
> Shout if you need help setting this out!

2022-04-09 21:09 UTC, fakela approved these changes

2022-04-09 21:10 UTC, merged