add Mautic Style guide
mautic/user-documentation pull request #67
Opened 2022-05-01 23:08 UTC by Kelvindest

2022-05-03 12:11 UTC, fakela commented
@Kelvindest thanks you did a wonderful job all vale checks passed 👍

2022-05-03 12:12 UTC, fakela commented
There is something missing links, i'll open a separate issue for that but this can be merged now that it is ready as it is a source of entry for new contributors

2022-05-04 09:29 UTC, fakela requested changes

2022-05-04 09:29 UTC, fakela commented on docs/contributing/mautic_style_guide.rst
> +#. Install vale
You need to add this link https://docs.errata.ai/vale/install to Vale, so its easier for users

2022-05-04 09:29 UTC, fakela commented on docs/contributing/mautic_style_guide.rst
> +
We need to add a section that explains how we link internal and external pages

2022-06-14 14:55 UTC, RCheesley commented
@fakela I have pushed some commits to address the feedback you left in the review - just double checking it renders OK on Gitpod.

2022-06-14 15:36 UTC, fakela commented
> Ready for review - the build errors are the links we are already aware of.

Alright it's good to go 🎉

2022-06-14 15:46 UTC, fakela approved these changes

2022-06-14 15:49 UTC, merged