Added new skeleton outline
mautic/user-documentation pull request #83
Opened 2022-06-21 23:24 UTC by favour-chibueze

2022-06-21 23:28 UTC, favour-chibueze commented
@RCheesley Please, review this PR. As I mentioned to you earlier, the Vale checks are failing on the Twilio links

2022-06-22 08:45 UTC, RCheesley requested changes
Looks good, just one small thing that I noticed which I think is an over-reactive Vale warning! Great work @favour-chibueze 🚀

2022-06-22 09:12 UTC, favour-chibueze commented on docs/getting_started/how_to_update_mautic.rst
> +- The live :xref:`Mautic Community Slack` is also available, but all support requests have to be posted on the forums. POST there first, then drop a link in Slack if you plan to discuss it there.
It's been resolved @RCheesley

2022-06-22 11:30 UTC, RCheesley approved these changes
Rock and roll, LGTM! 🎸 🚀

2022-06-22 11:30 UTC, merged