update overview of Mautic section
mautic/user-documentation pull request #85
Opened 2022-07-03 20:22 UTC by favour-chibueze

2022-07-04 11:17 UTC, RCheesley requested changes
Thanks for the work on this @favour-chibueze - I have made a bunch of recommendations for you to take a look at. Pinging @Robmobius for your thoughts on Knowledgebase or Knowledge base!

2022-07-04 11:18 UTC, RCheesley commented on docs/index.rst
> +:xref:`Knowledge Base` - Provides a database of tutorials, FAQs, and how-to articles.
@Robmobius here is the relevant part about the KB.

2022-07-14 12:15 UTC, RCheesley approved these changes
Good to go from my side! 🚀

2022-07-16 19:15 UTC, fakela commented
Looks good to me 👍

2022-07-16 19:15 UTC, fakela approved these changes

2022-07-19 13:14 UTC, merged